### ISSUE TITLE
File-based view

### ISSUE THREAD

**Issue by DevNatan** [DevNatan/inventory-framework#121]
Create view from file templates, proposal will be explained soon.
###### YAML format example
```yaml
title: "My view"
size: 3
type: chest
auto-update: 20
layout:
  - "XXXXXXXXX"
  - "XOOOOOOOX"
  - "XXXXXXXXX"
slots:
  1:
    item:
      # describe stack somehow
    actions:
      - "message 'Hello!!!'"
  2:
    item:
      # describe stack somehow
    actions:
      - "close"
```

## Context-specific
```yaml
context:
  title: "My view"
```

### VirtualView
| Name | Type | Description |
|------|------|-------------|
| title | string | The container title. |
| size | int32 | The container size. |
| type | string | The view type. |
| auto-update | int64 | View update interval (in ticks). |
| context | [VirtualView](#VirtualView) | |
